### ISSUE TITLE
Liens "Inscription|Connexion" présents dans le menu après validation de l'email

### ISSUE THREAD

**Issue by adrien-gueret** [adrien-gueret/ShyComics#19]
**Quoi ?**
Les liens *Inscription|Connexion* sont présents dans le menu en haut de la page comme si nous n'étions pas connectés alors qu'il est indiqué que nous le sommes.

![screen](https://cloud.githubusercontent.com/assets/1508585/6092132/a59e255a-aecf-11e4-8fce-4fa2f52b4fa4.png)

**Quand ?**
Au clic sur le lien de validation de l'email.

**Autres infos ?**
Lorsque je clique ensuite sur le logo du site pour revenir à la page d'accueil, le comportement attendu arrive : les liens disparaissent pour laisser place à *Bienvenue KorHosik | Me déconnecter*, signe que la connexion a bien eu lieu malgré le bug. Celui-ci est donc probablement qu'un soucis d'affichage.

**Comment by Tatane58** [comment]
J'ai envoyé une PR pour régler ton problème. ^^
